config/routes.rb
Rails.application.routes.draw do


  get 'comments/edit'

  root "posts#index"
  resources :posts do 
  	resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base #.all, .find(1) comes from here
	has_many :comments


	validates :title, presence: true, uniqueness: true
	validates :body, {length: {minimum: 100, maxmimum: 5000}}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:new, :create, :edit, :update]

  def new
  	#@post = Post.find(params[:post_id])
  	@comment = @post.comments.new
  end

  def create
  	#@post = Post.find(params[:post_id])
  	@comment = @post.comments.new(comment_params)
  	if @comment.save
  		flash[:success] ="Thanks for leaving a comment."
  		redirect_to post_path(@post)
  	else
  		flash[:error] ="Oops, something went wrong. Please try again."
  		render :new
  	end
  	
  end

  def update
  	@comment = @post.comments.find(params[:id])
  	if @comment.update(comment_params)
  		flash[:success] ="Comment has been updated"
  		redirect_to post_path(@post)
  	else
  		flash[:error] ="Oops, something went wrong. Please try again"
  		render :edit
  	end
  end
  	

  def edit
  	@comment = @post.comments.find(params[:id])
  end
  
  private
  def comment_params
  	params.require(:comment).permit(:body)
  end

  def find_post
  	@post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:index, :new, :create]
  def index
    #ActiveRecord gives us queries like Post.all. See app/models/post.rb 
    #GET all the posts from the posts table in DB
  if params[:featured].present? and params[:featured] =="true"
    #GET only the featured posts
    @posts = Post.where(is_featured:true).order("created_at desc")
  else

  	@posts = Post.order("created_at desc")
  end
  end

  def show
    #GET the post with the id from the url
  	#@post = Post.find(params["id"])
    @comments = @post.comments
  end
#############
  	def new
    @post = Post.new
  	end
# the new form gets submitted to the create action
  	def create
      @post = Post.new(post_params)
      if @post.save
        flash[:success] = "Thanks for posting!"
        redirect_to root_path
      else 
        flash[:error] ="Oops, something went wrong. Please try again"
        render :new
      end
  	end
 
#############
  	def edit
 #     @post =Post.find(params[:id])
  	end
#The edit form gets submitted to the update action
  	def update
  #    @post =Post.find(params[:id])
      if @post.update(post_params)
        flash[:success] ="Updated '#{@post.title}'"
        redirect_to post_path(@post)
      else
        render :edit
        flash[:error] ="ERROR"
      end
 	  end
#############
    def destroy
      flash[:success] ="Successfully deleted"
   #   @post = Post.find(params[:id])
      @post.destroy
      redirect_to root_path
    end
    
 private
 def post_params
  #allow attrivutes that i trust, ignore any scary malicious unsanctioned evil data
    params.require(:post).permit(:title, :body, :is_published, :is_featured)
  end

  def find_post
      @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Editing comment for "<%= @post.title %>"</h1>

<%=simple_form_for @comment, url: post_comment_path do |f| %>
	<%= f.input :body %>

	<%= f.button :submit %>

<% end %>

app/views/comments/new.html.erb
<h1>Comments <%=@post.title%></h1>
<%=simple_form_for @comment, url: post_comments_path do |f| %>
	<%= f.input :body %>

	<%= f.button :submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geopost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%=link_to "Home", root_path %>
		<%=link_to "Tell us a story", new_post_path%>
		<%=link_to "Recent", root_path%>
		<%=link_to "Featured", root_path(featured: true)%>
	</header>

	<% flash.each do |key, value| %>
	<div class="<%= key%>">
	<p><%=value%></p>
	</div>
	<%end%>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |form| %>
	
	<%= form.input :title %>
	<%= form.input :body %>
	<%= form.input :is_published %>
	<%= form.input :is_featured %>

	<div class="btn">
	<%= form.button :submit%>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit</h2>
<%= render "form" %>

app/views/posts/index.html.erb
<section class="posts">
	<% @posts.each do |post| %>
		<div class="post">
			<h2><%= link_to post.title, post_path(post) %></h2>
			<p><%=  post.body.truncate_words(10) %></p>
			<p>Posted <%= time_ago_in_words post.created_at %> ago</p>
		<div>
	<% end %>
</section>

app/views/posts/new.html.erb
<h2>New</h2>

<%= render "form" %>

app/views/posts/show.html.erb
<div class="post">
	<h1><%= @post.title%></h1>
	<%= simple_format @post.body%> 
	<p> Posted <%= time_ago_in_words @post.created_at%> ago.</p>
	<div class="actions">
		<%= link_to "Edit", edit_post_path(@post) %>
		<%= link_to "Comments", new_post_comment_path(@post) %>
		<%= link_to "Delete", post_path, method: :delete %>
	</div>

	<div class= "comment">
		<% @comments.each do |comment| %>
			<%= simple_format comment.body %>
			<p>Left <%= time_ago_in_words comment.created_at  %> ago.</p>
			<%= link_to "Edit", edit_post_comment_path(@post, comment) %>
		<% end %>
	</div>
</div>